version: "3.7"

services:
  web:
    container_name: geojson-convertor
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8012
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://postgres:secret@localhost:5438/uploads
      - CREDENTIALS_URL=http://localhost:8040/auth/credentials
      - FILE_EOL=10
    network_mode: host
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=uploads
    ports:
      - 5438:5432
volumes:
  postgres_data:
