version: "3.7"

services:
  web:
    container_name: geojson-convertor
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8012
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://postgres:secret@localhost:5439/uploads
      - CREDENTIALS_URL=http://localhost:8040/auth/credentials
      - FILE_EOL=10
      - ACCESS_TOKEN_KEY=token
      - REQUEST_ID_KEY=X-Request-ID
      - REQUEST_TIME_KEY=X-Process-Time
    ports:
      - 8088:8000
    network_mode: host
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=uploads
    ports:
      - 5439:5432
volumes:
  postgres_data:
